version: '3.4'

services:
  board-unittest:
    image: board-unitest
    command: bash -c "dotnet test --logger trx --collect:\"XPLAT Code Coverage\" --results-directory:/tests && chmod a+wr -R /tests"
    build:
      context: .
      dockerfile: Board/Dockerfile
      target: unittest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests

  board-ftest:
    image: board-ftest
    command: bash -c "dotnet test --logger trx --collect:\"XPLAT Code Coverage\" --results-directory:/tests && chmod a+wr -R /tests"
    build:
      context: .
      dockerfile: Board/Dockerfile
      target: ftest
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests